{{ if and (index .Values "modules" "generative-anyscale" "enabled") (index .Values "modules" "generative-anyscale" "apiKey") }}
apiVersion: v1
kind: Secret
metadata:
  name: weaviate-anyscale
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: helm
type: Opaque
data:
  apiKey: {{ index .Values "modules" "generative-anyscale" "apiKey" | b64enc }}
{{ end }}
