apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rag-nginx-ingress
  namespace: {{ .Values.namespace }}
  # https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#controller_summary
  annotations:
    kubernetes.io/ingress.class: "nginx" # which can be replaced by gce, gce-internal or istio
spec:
  rules:
  - host: {{ .Values.ingress.host }}  # You can also use "34.123.248.115.nip.io", please refer to https://github.com/GoogleCloudPlatform/community/blob/master/archived/nginx-ingress-gke/index.md
    http:
      paths:
      - path: /rag/docs
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: {{ .Values.service.httpPort.port }}
      - path: /rag/openapi.json
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: {{ .Values.service.httpPort.port }}
      - path: /query
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: {{ .Values.service.httpPort.port }}