apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.deployment.labels.appName }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.httpPort.port }}
      targetPort: {{ .Values.service.httpPort.targetPort }}
